/**
 * Shared contract between the ask-worker and the site widget.
 *
 * The worker streams Server-Sent Events; each `data:` payload is one
 * JSON-encoded {@link SseEvent}. Event order per request:
 *
 *   1. { sources } -- exactly once, may be an empty array
 *   2. { provider }-- exactly once, provider name (e.g. "gemini", "openrouter")
 *   3. { thinking }-- zero or more reasoning deltas (collapsible by UI)
 *   4. { text }    -- zero or more incremental answer deltas
 *   5. { done }    -- exactly once, terminal
 *
 * If/when ask-worker migrates to TypeScript it should import these types
 * so the two sides cannot drift.
 */

/** One document the answer was grounded on. */
export interface Source {
  readonly title: string;
  readonly url: string;
}

/** A single SSE payload from the ask-worker. */
export interface SseEvent {
  readonly sources?: readonly Source[];
  readonly provider?: string;
  readonly thinking?: string;
  readonly text?: string;
  readonly done?: boolean;
}

/** One prior conversational turn, as the worker expects it. */
export interface ChatTurn {
  readonly role: "user" | "assistant";
  readonly content: string;
}

/** Request body for POST {endpoint}. */
export interface AskRequest {
  readonly question: string;
  readonly history: readonly ChatTurn[];
}

/** Shape of /ask-config.json, generated by build-llms.py. */
export interface AskConfig {
  readonly enabled: boolean;
  readonly endpoint: string;
  readonly title: string;
  readonly placeholder: string;
  readonly llms_full_url: string;
}
