#!/usr/bin/env bash
set -euo pipefail

# ── Locate paths ─────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TEMPLATE_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
HOST_ROOT="$(cd "$TEMPLATE_ROOT/.." && pwd)"
GENDOC_YML="$HOST_ROOT/gendoc.yml"
WRANGLER_TOML="$TEMPLATE_ROOT/wrangler.toml"

# ── Validate prerequisites ───────────────────────────────────────────────────
if [ ! -f "$GENDOC_YML" ]; then
    echo "Error: gendoc.yml not found at $GENDOC_YML" >&2
    echo "       Create one by copying gendoc-template/gendoc.yml.example and filling in your project values." >&2
    exit 1
fi

if [ ! -f "$WRANGLER_TOML" ]; then
    echo "Error: wrangler.toml not found at $WRANGLER_TOML" >&2
    echo "       Run setup first: gendoc-template/scripts/setup.sh" >&2
    exit 1
fi

if ! command -v wrangler &>/dev/null; then
    echo "Error: wrangler not found." >&2
    echo "       Install with: npm install -g wrangler" >&2
    exit 1
fi

if ! wrangler whoami &>/dev/null; then
    echo "Error: not logged into Cloudflare." >&2
    echo "       Run: wrangler login" >&2
    exit 1
fi

# ── Read project name for display ────────────────────────────────────────────
PROJECT_NAME=$(python3 -c "
import yaml, sys
with open(sys.argv[1], 'r') as f:
    cfg = yaml.safe_load(f)
print(cfg.get('project', {}).get('name', ''), end='')
" "$GENDOC_YML")

echo "Deploying ${PROJECT_NAME:-(unnamed)} to Cloudflare Pages..."

# ── Deploy using the wrangler.toml generated by setup.sh ────────────────────
cd "$TEMPLATE_ROOT"

if wrangler pages deploy; then
    echo ""
    echo "=============================================="
    echo "  Deployment complete"
    echo "=============================================="
else
    exit_code=$?
    echo "Error: wrangler pages deploy failed with exit code $exit_code" >&2
    exit $exit_code
fi
