#!/usr/bin/env bash
set -euo pipefail

# ── Locate paths ─────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TEMPLATE_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
HOST_ROOT="$(cd "$TEMPLATE_ROOT/.." && pwd)"
GENDOC_YML="$HOST_ROOT/gendoc.yml"
WRANGLER_TOML="$TEMPLATE_ROOT/wrangler.toml"

# ── Activate Python virtual environment ────────────────────────────────────────
VENV="$TEMPLATE_ROOT/.venv"
if [ -d "$VENV" ]; then
    export PATH="$VENV/bin:$PATH"
fi

# ── Validate prerequisites ───────────────────────────────────────────────────
if [ ! -f "$GENDOC_YML" ]; then
    echo "Error: gendoc.yml not found at $GENDOC_YML" >&2
    echo "       Create one by copying gendoc-template/gendoc.yml.example and filling in your project values." >&2
    exit 1
fi

if [ ! -f "$WRANGLER_TOML" ]; then
    echo "Error: wrangler.toml not found at $WRANGLER_TOML" >&2
    echo "       Run setup first: gendoc-template/scripts/setup.sh" >&2
    exit 1
fi

if ! command -v wrangler &>/dev/null; then
    echo "Error: wrangler not found." >&2
    echo "       Install with: npm install -g wrangler" >&2
    exit 1
fi

if ! wrangler whoami &>/dev/null; then
    echo "Error: not logged into Cloudflare." >&2
    echo "       Run: wrangler login" >&2
    exit 1
fi

# ── CLI overrides ────────────────────────────────────────────────────────────
CLI_BRANCH=""
while [[ $# -gt 0 ]]; do
    case "$1" in
        --branch) CLI_BRANCH="$2"; shift 2 ;;
        *) echo "Unknown option: $1" >&2; exit 1 ;;
    esac
done

# ── Read configuration from gendoc.yml ──────────────────────────────────────────
mapfile -t GENDOC_VARS <<< "$(python3 -c "
import yaml, sys
with open(sys.argv[1], 'r') as f:
    cfg = yaml.safe_load(f)
name   = cfg.get('project', {}).get('name', '')
branch = cfg.get('deploy', {}).get('cloudflare', {}).get('branch', 'production')
print(name)
print(branch)
" "$GENDOC_YML")"
PROJECT_NAME="${GENDOC_VARS[0]}"
DEPLOY_BRANCH="${GENDOC_VARS[1]}"

# CLI --branch flag overrides gendoc.yml
DEPLOY_BRANCH="${CLI_BRANCH:-$DEPLOY_BRANCH}"

echo "Deploying ${PROJECT_NAME:-(unnamed)} to Cloudflare Pages (${DEPLOY_BRANCH})..."

# ── Deploy using the wrangler.toml generated by setup.sh ────────────────────
cd "$TEMPLATE_ROOT"

deploy_ok=true
if wrangler pages deploy --branch "$DEPLOY_BRANCH"; then
    echo ""
    echo "=============================================="
    echo "  Deployment complete"
    echo "=============================================="
else
    exit_code=$?
    echo "Error: deployment failed with exit code $exit_code" >&2
    deploy_ok=false
fi

if ! $deploy_ok; then
    exit $exit_code
fi
