#!/usr/bin/env bash
set -euo pipefail

# ── Locate paths ─────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TEMPLATE_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
HOST_ROOT="$(cd "$TEMPLATE_ROOT/.." && pwd)"
GENDOC_YML="$HOST_ROOT/gendoc.yml"
WRANGLER_TOML="$TEMPLATE_ROOT/wrangler.toml"

# ── Activate Python virtual environment ────────────────────────────────────────
VENV="$TEMPLATE_ROOT/.venv"
if [ -d "$VENV" ]; then
    export PATH="$VENV/bin:$PATH"
fi

# ── Validate prerequisites ───────────────────────────────────────────────────
if [ ! -f "$GENDOC_YML" ]; then
    echo "Error: gendoc.yml not found at $GENDOC_YML" >&2
    echo "       Create one by copying gendoc-template/gendoc.yml.example and filling in your project values." >&2
    exit 1
fi

if [ ! -f "$WRANGLER_TOML" ]; then
    echo "Error: wrangler.toml not found at $WRANGLER_TOML" >&2
    echo "       Run setup first: gendoc-template/scripts/setup.sh" >&2
    exit 1
fi

if ! command -v wrangler &>/dev/null; then
    echo "Error: wrangler not found." >&2
    echo "       Install with: npm install -g wrangler" >&2
    exit 1
fi

if ! wrangler whoami &>/dev/null; then
    echo "Error: not logged into Cloudflare." >&2
    echo "       Run: wrangler login" >&2
    exit 1
fi

# ── Read project name for display ────────────────────────────────────────────
PROJECT_NAME=$(python3 -c "
import yaml, sys
with open(sys.argv[1], 'r') as f:
    cfg = yaml.safe_load(f)
print(cfg.get('project', {}).get('name', ''), end='')
" "$GENDOC_YML")

echo "Deploying ${PROJECT_NAME:-(unnamed)} to Cloudflare Pages..."

# ── Read deploy configuration ─────────────────────────────────────────────────
DEPLOY_BRANCH=$(python3 -c "
import yaml, sys
with open(sys.argv[1], 'r') as f:
    cfg = yaml.safe_load(f)
print(cfg.get('deploy', {}).get('cloudflare', {}).get('branch', 'main'), end='')
" "$GENDOC_YML")

GZIP_JSON=$(python3 -c "
import yaml, sys
with open(sys.argv[1], 'r') as f:
    cfg = yaml.safe_load(f)
print(cfg.get('deploy', {}).get('cloudflare', {}).get('gzip_json', True), end='')
" "$GENDOC_YML")

# ── Prepare files for Cloudflare Pages (25 MiB per-file upload limit) ────────
echo "Preparing files for deployment..."
SITE_DIR="$TEMPLATE_ROOT/site"

if [ "$GZIP_JSON" = "True" ]; then
    # Uniform gzip for ALL .json files: gzip → .json.gz, delete raw .json.
    # The fetch-gzip.js wrapper handles transparent decompression at runtime.
    count=$(find "$SITE_DIR" -name "*.json" -type f ! -name "*.json.gz" | wc -l | tr -d ' ')
    while IFS= read -r -d '' f; do
        gzip -fk "$f" 2>/dev/null || true
        rm "$f"
    done < <(find "$SITE_DIR" -name "*.json" -type f ! -name "*.json.gz" -print0)
    echo "  Gzipped and removed $count .json files"
else
    echo "  Skipping JSON gzip (deploy.cloudflare.gzip_json is not True)"
fi

# ── Deploy using the wrangler.toml generated by setup.sh ────────────────────
cd "$TEMPLATE_ROOT"

deploy_ok=true
if wrangler pages deploy --branch "$DEPLOY_BRANCH"; then
    echo ""
    echo "=============================================="
    echo "  Deployment complete"
    echo "=============================================="
else
    exit_code=$?
    echo "Error: deployment failed with exit code $exit_code" >&2
    deploy_ok=false
fi

if ! $deploy_ok; then
    exit $exit_code
fi
